#!/usr/bin/env bash
set -euo pipefail

# Output DNS records needed for all configured domains.
# Reads config/domains.conf, config/mail-domains.conf, and config.env.
# Usage: bash infra/dns-records.sh

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
DOMAINS_FILE="${REPO_DIR}/config/domains.conf"
MAIL_DOMAINS_FILE="${REPO_DIR}/config/mail-domains.conf"
CONFIG_FILE="${REPO_DIR}/config.env"
[ -f "$CONFIG_FILE" ] || CONFIG_FILE="${SCRIPT_DIR}/config.env"

# Load config
SERVER_IP=""
MAIL_HOSTNAME=""
if [ -f "$CONFIG_FILE" ]; then
    SERVER_IP=$(grep -m1 "^SERVER_IP=" "$CONFIG_FILE" 2>/dev/null | cut -d= -f2- || true)
    MAIL_HOSTNAME=$(grep -m1 "^MAIL_HOSTNAME=" "$CONFIG_FILE" 2>/dev/null | cut -d= -f2- || true)
fi

: "${SERVER_IP:=<SERVER_IP>}"
: "${MAIL_HOSTNAME:=mail.fraefel.de}"

# Collect web domains
declare -A WEB_DOMAINS
if [ -f "$DOMAINS_FILE" ]; then
    while IFS= read -r line; do
        [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
        domain=$(echo "$line" | awk '{print $1}')
        backend=$(echo "$line" | awk '{print $2}')
        [ -z "$domain" ] && continue
        # Normalize redirect:target for display
        if [[ "$backend" == redirect:* ]]; then
            WEB_DOMAINS["$domain"]="redirect → ${backend#redirect:}"
        else
            WEB_DOMAINS["$domain"]="$backend"
        fi
    done < "$DOMAINS_FILE"
fi

# Collect mail domains
declare -A MAIL_DOMAINS
if [ -f "$MAIL_DOMAINS_FILE" ]; then
    while IFS= read -r line; do
        [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
        if [[ "$line" =~ ^\[(.+)\]$ ]]; then
            MAIL_DOMAINS["${BASH_REMATCH[1]}"]=1
        fi
    done < "$MAIL_DOMAINS_FILE"
fi

# Collect all unique domains
declare -A ALL_DOMAINS
for d in "${!WEB_DOMAINS[@]}"; do ALL_DOMAINS["$d"]=1; done
for d in "${!MAIL_DOMAINS[@]}"; do ALL_DOMAINS["$d"]=1; done

echo "============================================"
echo "  Dockbase DNS Records"
echo "  Server IP: ${SERVER_IP}"
echo "  Mail Host: ${MAIL_HOSTNAME}"
echo "============================================"
echo ""

# Sort domains for consistent output
for domain in $(echo "${!ALL_DOMAINS[@]}" | tr ' ' '\n' | sort); do
    has_web="${WEB_DOMAINS[$domain]:-}"
    has_mail="${MAIL_DOMAINS[$domain]:-}"

    echo "── ${domain} ──"

    if [ -n "$has_web" ]; then
        echo "  [Web: ${has_web}]"
    fi
    if [ -n "$has_mail" ]; then
        echo "  [Mail: yes]"
    fi
    echo ""

    # A record (for web domains and mail hostname)
    if [ -n "$has_web" ] || [ "$domain" = "$MAIL_HOSTNAME" ]; then
        printf "  %-30s  %-6s  %s\n" "@" "A" "${SERVER_IP}"
    fi

    # www CNAME (only for base domains with www variant in domains.conf)
    if [ -n "${WEB_DOMAINS[www.${domain}]:-}" ]; then
        printf "  %-30s  %-6s  %s\n" "www" "CNAME" "${domain}"
    fi

    # Mail records
    if [ -n "$has_mail" ]; then
        printf "  %-30s  %-6s  %s\n" "@" "MX" "10 ${MAIL_HOSTNAME}"
        printf "  %-30s  %-6s  %s\n" "@" "TXT" "\"v=spf1 mx a:${MAIL_HOSTNAME} ip4:${SERVER_IP} -all\""
        printf "  %-30s  %-6s  %s\n" "dkim._domainkey" "TXT" "(generated by Mailcow — get from UI or API)"
        printf "  %-30s  %-6s  %s\n" "_dmarc" "TXT" "\"v=DMARC1; p=quarantine; rua=mailto:postmaster@${domain}\""
        printf "  %-30s  %-6s  %s\n" "autoconfig" "CNAME" "${MAIL_HOSTNAME}"
        printf "  %-30s  %-6s  %s\n" "autodiscover" "CNAME" "${MAIL_HOSTNAME}"
    fi

    echo ""
done

# Show www domains separately (skip — already shown as CNAME under parent)
# Show subdomains
echo "── Subdomains ──"
for domain in $(echo "${!WEB_DOMAINS[@]}" | tr ' ' '\n' | sort); do
    # Detect subdomains (more than one dot, or known sub patterns)
    case "$domain" in
        mail.*|matomo.*)
            printf "  %-30s  %-6s  %s\n" "${domain}" "A" "${SERVER_IP}"
            ;;
    esac
done
echo ""
echo "Copy these records into your DNS provider."
