#!/usr/bin/env bash
set -euo pipefail

# Generate the shared edge Caddyfile from config/domains.conf
# Usage: bash infra/generate-caddyfile.sh
# Output: config/caddy/Caddyfile (overwritten)

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
DOMAINS_FILE="${REPO_DIR}/config/domains.conf"
OUTPUT_FILE="${REPO_DIR}/config/caddy/Caddyfile"
CONFIG_FILE="${REPO_DIR}/config.env"
[ -f "$CONFIG_FILE" ] || CONFIG_FILE="${SCRIPT_DIR}/config.env"

if [ ! -f "$DOMAINS_FILE" ]; then
    echo "ERROR: ${DOMAINS_FILE} not found"
    exit 1
fi

# Read TLS_EMAIL from config.env if available
TLS_EMAIL=""
if [ -f "$CONFIG_FILE" ]; then
    TLS_EMAIL=$(grep -m1 "^TLS_EMAIL=" "$CONFIG_FILE" 2>/dev/null | cut -d= -f2- || true)
fi

# ── Parse domains.conf: group domains by backend ─────────
declare -A BACKEND_DOMAINS

while IFS= read -r line; do
    # Skip blanks and comments
    [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
    domain=$(echo "$line" | awk '{print $1}')
    backend=$(echo "$line" | awk '{print $2}')
    [ -z "$domain" ] || [ -z "$backend" ] && continue
    # Redirects are grouped by target: redirect:fraefel.de
    BACKEND_DOMAINS["$backend"]+="${domain} "
done < "$DOMAINS_FILE"

# ── Security headers snippet ─────────────────────────────
SECURITY_HEADERS='    header {
        Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
        X-Content-Type-Options "nosniff"
        X-Frame-Options "SAMEORIGIN"
        X-XSS-Protection "1; mode=block"
        Referrer-Policy "strict-origin-when-cross-origin"
        Permissions-Policy "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), usb=()"
        -Server
    }'

LOG_BLOCK='    log {
        output file /var/log/caddy/access.log
        format json
    }'

# ── Generate Caddyfile ───────────────────────────────────
{
    echo "# Dockbase shared edge Caddyfile"
    echo "# AUTO-GENERATED by infra/generate-caddyfile.sh — do not edit manually"
    echo "#"
    echo "{"
    if [ -n "$TLS_EMAIL" ]; then
        echo "    email ${TLS_EMAIL}"
    fi
    echo "}"
    echo ""

    # ── Shop backend ─────────────────────────────────────
    if [ -n "${BACKEND_DOMAINS[shop]:-}" ]; then
        # Trim trailing space, join with spaces (Caddy site block syntax)
        domains=$(echo "${BACKEND_DOMAINS[shop]}" | xargs)
        echo "${domains} {"
        echo "${SECURITY_HEADERS}"
        echo ""
        echo "    # Shop content security policy"
        echo '    header Content-Security-Policy "default-src '\''self'\''; script-src '\''self'\'' '\''unsafe-inline'\'' '\''unsafe-eval'\'' https:; style-src '\''self'\'' '\''unsafe-inline'\'' https:; img-src '\''self'\'' data: https:; connect-src '\''self'\'' https:; frame-src '\''self'\'' blob: https:; font-src '\''self'\'' https: data:; worker-src '\''self'\'' blob:; object-src '\''none'\''; base-uri '\''self'\'';"'
        echo ""
        echo "    encode zstd gzip"
        echo "    reverse_proxy frankenphp:8080"
        echo ""
        echo "${LOG_BLOCK}"
        echo "}"
        echo ""
    fi

    # ── Website backend ──────────────────────────────────
    if [ -n "${BACKEND_DOMAINS[website]:-}" ]; then
        domains=$(echo "${BACKEND_DOMAINS[website]}" | xargs)
        echo "${domains} {"
        echo "${SECURITY_HEADERS}"
        echo ""
        echo "    root * /srv/website/public"
        echo "    encode zstd gzip"
        echo "    file_server"
        echo ""
        echo "${LOG_BLOCK}"
        echo "}"
        echo ""
    fi

    # ── Mailweb backend ──────────────────────────────────
    if [ -n "${BACKEND_DOMAINS[mailweb]:-}" ]; then
        domains=$(echo "${BACKEND_DOMAINS[mailweb]}" | xargs)
        echo "${domains} {"
        echo "${SECURITY_HEADERS}"
        echo ""
        echo "    reverse_proxy host.docker.internal:8880 {"
        echo "        header_up X-Forwarded-Proto {scheme}"
        echo "    }"
        echo ""
        echo "${LOG_BLOCK}"
        echo "}"
        echo ""
    fi

    # ── Matomo shop backend ──────────────────────────────
    if [ -n "${BACKEND_DOMAINS[matomo-shop]:-}" ]; then
        domains=$(echo "${BACKEND_DOMAINS[matomo-shop]}" | xargs)
        echo "${domains} {"
        echo "${SECURITY_HEADERS}"
        echo ""
        echo "    reverse_proxy matomo-shop:80 {"
        echo "        header_down -Content-Security-Policy"
        echo "    }"
        echo ""
        echo "${LOG_BLOCK}"
        echo "}"
        echo ""
    fi

    # ── Matomo web backend ───────────────────────────────
    if [ -n "${BACKEND_DOMAINS[matomo-web]:-}" ]; then
        domains=$(echo "${BACKEND_DOMAINS[matomo-web]}" | xargs)
        echo "${domains} {"
        echo "${SECURITY_HEADERS}"
        echo ""
        echo "    reverse_proxy matomo-web:80 {"
        echo "        header_down -Content-Security-Policy"
        echo "    }"
        echo ""
        echo "${LOG_BLOCK}"
        echo "}"
        echo ""
    fi

    # ── Redirect backends ─────────────────────────────────
    for key in "${!BACKEND_DOMAINS[@]}"; do
        [[ "$key" == redirect:* ]] || continue
        target="${key#redirect:}"
        domains=$(echo "${BACKEND_DOMAINS[$key]}" | xargs)
        echo "${domains} {"
        echo "    redir https://${target}{uri} permanent"
        echo "}"
        echo ""
    done

} > "$OUTPUT_FILE"

echo "Generated: ${OUTPUT_FILE}"
echo "Backends found: ${!BACKEND_DOMAINS[*]}"
